import { StyleSheet } from 'react-native'
import type { useTheme } from '../../../../../src/theme'

export function makeStyles(theme: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    flex: { flex: 1 },
    center: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.background,
    },
    container: { flex: 1, backgroundColor: theme.colors.background },
    content: { padding: theme.spacing.xl, paddingBottom: theme.spacing.xl * 2 },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: theme.spacing.md,
      marginTop: theme.spacing.xl,
    },
    back: {},
    backText: {
      color: theme.colors.primary,
      fontSize: theme.typography.size.sm,
      fontWeight: theme.typography.weight.medium,
    },
    editBtn: {
      backgroundColor: theme.colors.surface,
      paddingVertical: theme.spacing.xs,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.borderRadius.sm,
    },
    editBtnText: {
      color: theme.colors.primary,
      fontSize: theme.typography.size.sm,
      fontWeight: theme.typography.weight.medium,
    },
    cancelBtn: {
      paddingVertical: theme.spacing.xs,
      paddingHorizontal: theme.spacing.md,
    },
    cancelBtnText: {
      color: theme.colors.navyMuted,
      fontSize: theme.typography.size.sm,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: theme.spacing.md,
      marginBottom: theme.spacing.xl,
    },
    typeIconLg: { fontSize: 36, marginTop: 2 },
    headerInfo: { flex: 1 },
    name: {
      fontSize: theme.typography.size.xxl,
      fontWeight: theme.typography.weight.bold,
      color: theme.colors.navy,
    },
    address: {
      fontSize: theme.typography.size.sm,
      color: theme.colors.navyMuted,
      marginTop: theme.spacing.xs,
    },
    section: { marginBottom: theme.spacing.xl },
    sectionTitle: {
      fontSize: theme.typography.size.md,
      fontWeight: theme.typography.weight.semiBold,
      color: theme.colors.navy,
      marginBottom: theme.spacing.md,
    },
    emptyMeta: {
      fontSize: theme.typography.size.sm,
      color: theme.colors.navyMuted,
      fontStyle: 'italic',
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
    },
    infoIcon: { fontSize: 18 },
    infoLink: {
      fontSize: theme.typography.size.md,
      color: theme.colors.primary,
      flex: 1,
    },
    hoursBox: {
      marginTop: theme.spacing.sm,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
      padding: theme.spacing.md,
      gap: theme.spacing.xs,
    },
    hoursTitle: {
      fontSize: theme.typography.size.xs,
      fontWeight: theme.typography.weight.semiBold,
      color: theme.colors.navyMuted,
      marginBottom: theme.spacing.xs,
    },
    hoursRow: { fontSize: theme.typography.size.sm, color: theme.colors.navy },
    readRow: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
      padding: theme.spacing.md,
      marginBottom: theme.spacing.sm,
    },
    readLabel: {
      fontSize: theme.typography.size.xs,
      color: theme.colors.navyMuted,
      fontWeight: theme.typography.weight.medium,
      marginBottom: 2,
    },
    readValue: {
      fontSize: theme.typography.size.md,
      color: theme.colors.navy,
      fontWeight: theme.typography.weight.medium,
    },
    editSection: { gap: theme.spacing.sm },
    label: {
      fontSize: theme.typography.size.sm,
      fontWeight: theme.typography.weight.semiBold,
      color: theme.colors.navy,
      marginBottom: theme.spacing.xs,
      marginTop: theme.spacing.md,
    },
    input: {
      padding: theme.spacing.md,
      fontSize: theme.typography.size.md,
      color: theme.colors.navy,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
    },
    inputMultiline: { minHeight: 80, textAlignVertical: 'top' },
    currentAddress: {
      fontSize: theme.typography.size.sm,
      color: theme.colors.navyMuted,
      paddingHorizontal: theme.spacing.xs,
      marginBottom: theme.spacing.xs,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
    },
    searchInput: {
      flex: 1,
      padding: theme.spacing.md,
      fontSize: theme.typography.size.md,
      color: theme.colors.navy,
    },
    searchSpinner: { marginRight: theme.spacing.md },
    detailsSpinner: { marginTop: theme.spacing.sm },
    suggestions: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.borderRadius.md,
      marginTop: theme.spacing.xs,
      overflow: 'hidden',
    },
    suggestion: {
      padding: theme.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.background,
    },
    suggestionMain: {
      fontSize: theme.typography.size.md,
      fontWeight: theme.typography.weight.medium,
      color: theme.colors.navy,
    },
    suggestionSecondary: {
      fontSize: theme.typography.size.xs,
      color: theme.colors.navyMuted,
      marginTop: 2,
    },
    typeRow: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
      flexWrap: 'wrap',
      marginTop: theme.spacing.xs,
    },
    typeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
      borderRadius: theme.borderRadius.md,
      backgroundColor: theme.colors.surface,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    typeButtonActive: { borderColor: theme.colors.primary },
    typeIcon: { fontSize: 16 },
    typeLabel: {
      fontSize: theme.typography.size.sm,
      color: theme.colors.navyMuted,
      fontWeight: theme.typography.weight.medium,
    },
    typeLabelActive: { color: theme.colors.primary },
    saveButton: {
      backgroundColor: theme.colors.primary,
      padding: theme.spacing.md,
      borderRadius: theme.borderRadius.md,
      alignItems: 'center',
      marginTop: theme.spacing.xl,
    },
    saveText: {
      color: theme.colors.white,
      fontSize: theme.typography.size.md,
      fontWeight: theme.typography.weight.semiBold,
    },
    deleteButton: {
      padding: theme.spacing.md,
      borderRadius: theme.borderRadius.md,
      alignItems: 'center',
      marginTop: theme.spacing.sm,
      borderWidth: 1,
      borderColor: theme.colors.error,
    },
    deleteText: {
      color: theme.colors.error,
      fontSize: theme.typography.size.md,
      fontWeight: theme.typography.weight.medium,
    },
  })
}
